server:
  port: 5000
  TCPPort: :54809
  UDPPort: :54810
datasource:
  driverName: mysql
  host: 47.106.96.238
  port: 3306
  database: regicide
  username: root
  password: txtx54TX!
  charset: utf8
GoPool:
  Open: true
  poolSize: 300
